spring.application.name=attendance-management
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/attendance_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:attendance_user}
spring.datasource.password=${DB_PASSWORD:StrongPass123!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
